from __future__ import annotations

from typing import Protocol

from app.domain.entities.account import Account


class AccountRepository(Protocol):
    def get_by_id(self, account_id: int) -> Account | None: ...

    def get_by_number(self, number: str) -> Account | None: ...

    def list(self) -> list[Account]: ...

    def list_by_customer(self, customer_id: int) -> list[Account]: ...

    def add(self, account: Account) -> Account: ...

    def update(self, account: Account) -> Account: ...

    def delete(self, account: Account) -> None: ...

    def has_pix_keys(self, account_id: int) -> bool: ...

    def has_transactions(self, account_id: int) -> bool: ...
