from typing import Protocol

from app.domain.entities.customer import Customer


class CustomerRepository(Protocol):
    def get_by_id(self, customer_id: int) -> Customer | None: ...

    def list(self) -> list[Customer]: ...

    def get_by_email(self, email: str) -> Customer | None: ...

    def get_by_cpf(self, cpf: str) -> Customer | None: ...

    def add(self, customer: Customer) -> Customer: ...

    def update(self, customer: Customer) -> Customer: ...

    def delete(self, customer: Customer) -> None: ...
