from __future__ import annotations

from typing import Protocol

from app.domain.entities.pix_key import PixKey


class PixKeyRepository(Protocol):
    def get_by_id(self, pix_key_id: int) -> PixKey | None: ...

    def get_by_value(self, value: str) -> PixKey | None: ...

    def list(self) -> list[PixKey]: ...

    def list_by_account(self, account_id: int) -> list[PixKey]: ...

    def add(self, pix_key: PixKey) -> PixKey: ...

    def update(self, pix_key: PixKey) -> PixKey: ...

    def delete(self, pix_key: PixKey) -> None: ...
