"""initial schema

Revision ID: 7af7709706ad
Revises: 
Create Date: 2026-09-09 14:01:24.676340

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7af7709706ad"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("cpf", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("role IN ('ADMIN','CUSTOMER')", name="ck_customers_role"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cpf"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("agency", sa.String(), nullable=False),
        sa.Column("number", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("balance_cents", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("balance_cents >= 0", name="ck_accounts_balance_non_negative"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    op.create_index(op.f("ix_accounts_customer_id"), "accounts", ["customer_id"], unique=False)
    op.create_table(
        "pix_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("type IN ('CPF','EMAIL','PHONE','RANDOM')", name="ck_pix_keys_type"),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("value"),
    )
    op.create_index(op.f("ix_pix_keys_account_id"), "pix_keys", ["account_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_account_id", sa.Integer(), nullable=True),
        sa.Column("destination_account_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "type IN ('DEPOSIT','WITHDRAW','PIX_TRANSFER')", name="ck_transactions_type"
        ),
        sa.CheckConstraint("amount_cents > 0", name="ck_transactions_amount_positive"),
        sa.ForeignKeyConstraint(["destination_account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_destination_account_id"),
        "transactions",
        ["destination_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_source_account_id"),
        "transactions",
        ["source_account_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_source_account_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_destination_account_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_pix_keys_account_id"), table_name="pix_keys")
    op.drop_table("pix_keys")
    op.drop_index(op.f("ix_accounts_customer_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_table("customers")
    # ### end Alembic commands ###
