from __future__ import annotations

from typing import Protocol

from app.domain.entities.account import Account
from app.domain.entities.transaction import Transaction


class AccountUseCases(Protocol):
    def create(
        self, customer_id: int, agency: str, number: str, label: str | None = None
    ) -> Account: ...

    def list(self) -> list[Account]: ...

    def list_by_customer(self, customer_id: int) -> list[Account]: ...

    def get(self, account_id: int) -> Account: ...

    def update(self, account_id: int, agency: str | None, label: str | None) -> Account: ...

    def delete(self, account_id: int) -> None: ...

    def deposit(self, account_id: int, amount_cents: int) -> Transaction: ...

    def withdraw(self, account_id: int, amount_cents: int) -> Transaction: ...

    def get_statement(self, account_id: int) -> list[Transaction]: ...
